주피터 노트북이 현재 어떤 환경에서 실행되고 있는지 확인하는 방법
주피터 노트북을 폴더에서 바로 실행하면, 어떤 가상환경(예: conda 환경, base 등)에서 실행 중인지 헷갈릴 수 있습니다. 아래 방법으로 현재 노트북이 사용하는 환경을 쉽게 확인할 수 있습니다.

In [1]:
#환경 확인
import sys
print(sys.executable)


C:\Users\82109\miniconda3\python.exe


환경 이름만 간단히 확인

In [2]:
import os
print(os.environ.get('CONDA_DEFAULT_ENV'))

base


In [3]:
import numpy as np
print(np.__version__)

2.3.1


In [4]:
# 1. 1차원 배열 생성
array1 = np.array([1,3,5,6,7,9])   # [1, 3, 5, 6, 7, 9]로 구성된 1차원 배열 생성
array1                             # 배열 내용 출력

array([1, 3, 5, 6, 7, 9])

In [5]:
# 2. 0으로 채워진 배열 생성
np.zeros(5)                        # 0으로 채워진 길이 5짜리 1차원 배열 생성

array([0., 0., 0., 0., 0.])

In [6]:
# 3. 연속된 정수 배열 생성
np.arange(10)                      # 0부터 9까지의 정수로 이루어진 1차원 배열 생성 (10은 포함하지 않음)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,10)                    # 2부터 9까지의 정수로 이루어진 1차원 배열 생성 (10은 포함하지 않음)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(4,17,3)                  # 4부터 16까지 3씩 증가하는 값들로 이루어진 배열 생성 (17은 포함하지 않음)

array([ 4,  7, 10, 13, 16])

In [9]:
# 4. 배열의 타입 확인
type(array1)                       # array1의 자료형(타입) 확인, 보통 <class 'numpy.ndarray'>로 출력됨

numpy.ndarray

In [10]:
# 5. 2차원 배열 생성
array2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])                                 # 3행 4열의 2차원 배열 생성
array2                             # 배열 내용 출력

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# 6. 2차원 배열의 타입 확인
type(array2)                       # array2의 자료형(타입) 확인, <class 'numpy.ndarray'>

numpy.ndarray

In [12]:
# 7. 배열의 원소 개수 및 형태 확인
array1.size                        # array1의 전체 원소 개수 (6)

6

In [13]:
array1.shape                       # array1의 배열 형태(차원), (6,) → 1차원에 6개 원소

(6,)

In [14]:
array2.size                        # array2의 전체 원소 개수 (12)

12

In [15]:
array2.shape                       # array2의 배열 형태(차원), (3, 4) → 3행 4열

(3, 4)

In [16]:
# 1. GDP 데이터로 1차원 넘파이 배열 생성
gdp_array = np.array([6610, 7637, 8127, 8885, 10385, 12565, 13403, 12398, 8282, 10672])
gdp_array  # 배열 전체 출력

array([ 6610,  7637,  8127,  8885, 10385, 12565, 13403, 12398,  8282,
       10672])

In [17]:
# 2. 배열의 마지막 원소 조회 (음수 인덱스 사용) 
#  0 1 2 3 4 5 6 7 8 9
#-10-9-8-7-6-5-4-3-2-1
gdp_array[-1]  # 10672 (마지막 연도의 GDP)

np.int64(10672)

In [18]:
# 3. 배열에서 여러 개의 특정 위치 값만 추출 (Fancy Indexing)
gdp_array[[1, 3, 4]]  # [7637, 8885, 10385] (2번째, 4번째, 5번째 값)

array([ 7637,  8885, 10385])

In [19]:
# 4. 다른 배열을 인덱스로 사용해 값 추출
arr1 = np.array([2, 1, 3, 5])
gdp_array[arr1]  # [8127, 7637, 8885, 12565] (arr1이 지정한 위치의 값들)

array([ 8127,  7637,  8885, 12565])

In [20]:
# 5. 슬라이싱: 2번째부터 3번째까지 (인덱스 2~3)
gdp_array[2:4]  # [8127, 8885] (3번째, 4번째 값)

array([8127, 8885])

In [21]:
# 6. 슬라이싱: 처음부터 2번째까지 (인덱스 0~2)
gdp_array[:3]  # [6610, 7637, 8127] (처음 3개 값)

array([6610, 7637, 8127])

In [22]:
# 7. 슬라이싱: 8번째부터 끝까지 (인덱스 7~끝)
gdp_array[7:]  # [12398, 8282, 10672] (마지막 3개 값)

array([12398,  8282, 10672])

In [23]:
# 8. 슬라이싱: 2번째부터 8번째까지, 3칸씩 건너뛰며 추출 (인덱스 1, 4, 7)
gdp_array[1:8:3]  # [7637, 10385, 12398]

array([ 7637, 10385, 12398])

In [24]:
# 4개 국가(대한민국, 일본, 중국, 미국)의 연도별 GDP 데이터로 2차원 배열 생성
gdp_array2 = np.array([
    [12257, 11561, 13165, 14673, 16496, 19403],  # 대한민국
    [39169, 34406, 32821, 35387, 38299, 37813],  # 일본
    [959, 1053, 1149, 1289, 1509, 1753],         # 중국
    [36335, 37133, 38023, 39496, 41713, 44115]   # 미국
])

In [25]:
gdp_array2  # 전체 2차원 배열 출력 (4개 국가 x 6개 연도)

array([[12257, 11561, 13165, 14673, 16496, 19403],
       [39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753],
       [36335, 37133, 38023, 39496, 41713, 44115]])

In [26]:
gdp_array2[1]        # 일본의 모든 연도별 GDP (2번째 행 전체 추출)

array([39169, 34406, 32821, 35387, 38299, 37813])

In [27]:
gdp_array2[1][3]     # 일본의 4번째 연도 GDP (2번째 행, 4번째 열 값: 35387)

np.int64(35387)

In [28]:
gdp_array2[1:3,2:5]  # 일본, 중국(2~3번째 행)의 3~5번째 연도 GDP (열 index 2~4)

array([[32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [29]:
gdp_array2[1:3,2:]   # 일본, 중국의 3번째 연도부터 마지막까지 GDP (열 index 2~끝)

array([[32821, 35387, 38299, 37813],
       [ 1149,  1289,  1509,  1753]])

In [30]:
gdp_array2[:3, 2:5]  # 대한민국, 일본, 중국(0~2번째 행)의 3~5번째 연도 GDP

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509]])

In [31]:
gdp_array2[:,2:5]    # 모든 국가의 3~5번째 연도 GDP (열 index 2~4)

array([[13165, 14673, 16496],
       [32821, 35387, 38299],
       [ 1149,  1289,  1509],
       [38023, 39496, 41713]])

In [32]:
gdp_array2[1:3,:]    # 일본, 중국(1~2번째 행)의 모든 연도 GDP (전체 열)

array([[39169, 34406, 32821, 35387, 38299, 37813],
       [  959,  1053,  1149,  1289,  1509,  1753]])

In [33]:
# 1. 각 값이 10000보다 큰지 비교 (Boolean 배열 생성)
gdp_array > 10000              # [False False False False  True  True  True  True False  True]

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [34]:
# 2. 10000보다 큰 값만 골라내는 마스크(조건) 생성
mask = gdp_array > 10000       # mask: [False False False False  True  True  True  True False  True]

In [35]:
# 3. 마스크를 사용해 10000 초과 값만 추출 (Boolean 인덱싱)
gdp_array[mask]                # [10385 12565 13403 12398 10672]

array([10385, 12565, 13403, 12398, 10672])

In [36]:
# 4. 조건식을 바로 인덱싱에 사용해도 동일 (inline Boolean 인덱싱)
gdp_array[gdp_array > 10000]   # [10385 12565 13403 12398 10672]

array([10385, 12565, 13403, 12398, 10672])

In [37]:
# 5. 각 값이 10000보다 큰지 Boolean 배열로 확인
gdp_array > 10000              # [False False False False  True  True  True  True False  True]

array([False, False, False, False,  True,  True,  True,  True, False,
        True])

In [38]:
# 6. 각 값이 8000보다 작은지 Boolean 배열로 확인
gdp_array < 8000               # [ True  True False False False False False False  True False]

array([ True,  True, False, False, False, False, False, False, False,
       False])

In [39]:
# 7. 10000 초과 또는 8000 미만인 값 찾기 (조건 결합: OR)
(gdp_array > 10000) | (gdp_array < 8000)  # [ True  True False False  True  True  True  True  True  True]

array([ True,  True, False, False,  True,  True,  True,  True, False,
        True])

In [40]:
# 8. 위 조건을 만족하는 값들만 추출
gdp_array[(gdp_array > 10000) | (gdp_array < 8000)]  # [ 6610  7637 10385 12565 13403 12398  8282 10672]

array([ 6610,  7637, 10385, 12565, 13403, 12398, 10672])

In [41]:
# 9. 8000 이상 10000 이하인 값만 추출 (조건 결합: AND)
gdp_array[(gdp_array <= 10000) & (gdp_array >= 8000)]  # [8127 8885]

array([8127, 8885, 8282])

In [42]:
# 대한민국의 연도별 GDP 데이터만 추출 (1차원 배열)
gdp_korea_array = gdp_array2[0]
gdp_korea_array  # [12257, 11561, 13165, 14673, 16496, 19403]

array([12257, 11561, 13165, 14673, 16496, 19403])

In [43]:
# 대한민국 GDP의 평균값 계산
gdp_korea_array.mean()  # 배열의 평균 (평균 GDP)

np.float64(14592.5)

In [44]:
# 대한민국 GDP의 총합 계산
gdp_korea_array.sum()   # 배열의 합계 (전체 기간 GDP 합)

np.int64(87555)

In [45]:
# 대한민국 GDP 중 최소값 찾기
gdp_korea_array.min()   # 배열의 최소값 (가장 낮은 연도 GDP)

np.int64(11561)

In [46]:
# 대한민국 GDP 중 최대값 찾기
gdp_korea_array.max()   # 배열의 최대값 (가장 높은 연도 GDP)

np.int64(19403)

In [47]:
# # for문으로 각 원소에 1200 곱하기 (주석 처리, 아래 벡터 연산으로 대체)
# for i in range(len(gdp_korea_array)):
#     gdp_korea_array[i] = gdp_korea_array[i] * 1200

# 벡터 연산: 배열 전체에 1200 곱하기 (원본은 변하지 않음)
gdp_korea_array * 1200  # 모든 연도 GDP를 1200배 (예: 달러→원 환산 등)

array([14708400, 13873200, 15798000, 17607600, 19795200, 23283600])

In [48]:
# 원본 배열은 그대로 유지됨
gdp_korea_array  # [12257, 11561, 13165, 14673, 16496, 19403]

array([12257, 11561, 13165, 14673, 16496, 19403])

In [49]:
# 배열 전체에 1200 곱한 결과를 다시 변수에 저장 (원본 덮어쓰기)
gdp_korea_array = gdp_korea_array * 1200
gdp_korea_array  # [14708400, 13873200, 15798000, 17607600, 19795200, 23283600]

array([14708400, 13873200, 15798000, 17607600, 19795200, 23283600])

In [50]:
# 배열 전체를 1200으로 나눠서 다시 원래 값으로 복원
gdp_korea_array = gdp_korea_array / 1200
gdp_korea_array  # [12257., 11561., 13165., 14673., 16496., 19403.]

array([12257., 11561., 13165., 14673., 16496., 19403.])

In [51]:
# 다시 대한민국 GDP 원본 배열로 복원
gdp_korea_array = gdp_array2[0]

In [52]:
# 미국의 연도별 GDP 데이터 추출
gdp_us_array = gdp_array2[3]

In [53]:
# 미국 GDP에서 대한민국 GDP를 뺀 차이 (각 연도별 국가 간 GDP 차이)
gdp_us_array - gdp_korea_array  # [24078, 25572, 24858, 24823, 25217, 24712]

array([24078, 25572, 24858, 24823, 25217, 24712])

In [54]:
# 미국 GDP를 대한민국 GDP로 나눈 비율 (각 연도별 미국/한국 GDP 배수)
gdp_us_array / gdp_korea_array  # [2.965..., 3.214..., 2.889..., 2.694..., 2.529..., 2.273...]

array([2.96442849, 3.21191938, 2.88818838, 2.69174675, 2.52867362,
       2.27361748])

In [57]:
# 1부터 100까지의 정수로 이루어진 1차원 배열 생성 (100 포함)
numbers_array = np.arange(1, 101)

# numbers_array에서 2로 나누어 떨어지는(짝수) 값만 추출 (Boolean 인덱싱)
numbers_array[numbers_array % 2 == 0]
# → numbers_array의 각 원소에 대해 2로 나눈 나머지가 0인 값(짝수)만 골라서 반환
# 결과: [  2   4   6 ... 100]

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [55]:
import pandas as pd
import matplotlib
print(pd.__version__)
print(matplotlib.__version__)

2.2.3
3.10.0
