주피터 노트북이 현재 어떤 환경에서 실행되고 있는지 확인하는 방법
주피터 노트북을 폴더에서 바로 실행하면, 어떤 가상환경(예: conda 환경, base 등)에서 실행 중인지 헷갈릴 수 있습니다. 아래 방법으로 현재 노트북이 사용하는 환경을 쉽게 확인할 수 있습니다.

In [1]:
#환경 확인
import sys
print(sys.executable)


C:\Users\82109\miniconda3\python.exe


환경 이름만 간단히 확인

In [2]:
import os
print(os.environ.get('CONDA_DEFAULT_ENV'))

base


In [3]:
import numpy as np
print(np.__version__)

2.3.1


In [4]:
# 1. 1차원 배열 생성
array1 = np.array([1,3,5,6,7,9])   # [1, 3, 5, 6, 7, 9]로 구성된 1차원 배열 생성
array1                             # 배열 내용 출력

array([1, 3, 5, 6, 7, 9])

In [5]:
# 2. 0으로 채워진 배열 생성
np.zeros(5)                        # 0으로 채워진 길이 5짜리 1차원 배열 생성

array([0., 0., 0., 0., 0.])

In [6]:
# 3. 연속된 정수 배열 생성
np.arange(10)                      # 0부터 9까지의 정수로 이루어진 1차원 배열 생성 (10은 포함하지 않음)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
np.arange(2,10)                    # 2부터 9까지의 정수로 이루어진 1차원 배열 생성 (10은 포함하지 않음)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.arange(4,17,3)                  # 4부터 16까지 3씩 증가하는 값들로 이루어진 배열 생성 (17은 포함하지 않음)

array([ 4,  7, 10, 13, 16])

In [9]:
# 4. 배열의 타입 확인
type(array1)                       # array1의 자료형(타입) 확인, 보통 <class 'numpy.ndarray'>로 출력됨

numpy.ndarray

In [10]:
# 5. 2차원 배열 생성
array2 = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,10,11,12]
])                                 # 3행 4열의 2차원 배열 생성
array2                             # 배열 내용 출력

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [11]:
# 6. 2차원 배열의 타입 확인
type(array2)                       # array2의 자료형(타입) 확인, <class 'numpy.ndarray'>

numpy.ndarray

In [12]:
# 7. 배열의 원소 개수 및 형태 확인
array1.size                        # array1의 전체 원소 개수 (6)

6

In [13]:
array1.shape                       # array1의 배열 형태(차원), (6,) → 1차원에 6개 원소

(6,)

In [14]:
array2.size                        # array2의 전체 원소 개수 (12)

12

In [15]:
array2.shape                       # array2의 배열 형태(차원), (3, 4) → 3행 4열

(3, 4)

In [16]:
import pandas as pd
import matplotlib
print(pd.__version__)
print(matplotlib.__version__)

2.2.3
3.10.0
