주피터 노트북이 현재 어떤 환경에서 실행되고 있는지 확인하는 방법
주피터 노트북을 폴더에서 바로 실행하면, 어떤 가상환경(예: conda 환경, base 등)에서 실행 중인지 헷갈릴 수 있습니다. 아래 방법으로 현재 노트북이 사용하는 환경을 쉽게 확인할 수 있습니다.

In [2]:
#환경 확인
import sys
print(sys.executable)


C:\Users\82109\miniconda3\python.exe


환경 이름만 간단히 확인

In [3]:
import os
print(os.environ.get('CONDA_DEFAULT_ENV'))

base


In [5]:
import numpy as np
print(np.__version__)

2.3.1


In [8]:
array1 = np.array([1,3,5,6,7,9])
array1

array([1, 3, 5, 6, 7, 9])

In [9]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(2,10)

array([2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(4,17,3)

array([ 4,  7, 10, 13, 16])

In [14]:
type(array1)

numpy.ndarray

In [19]:
array2 = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
array2

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [24]:
type(array2)

numpy.ndarray

In [20]:
array1.size

6

In [23]:
array1.shape

(6,)

In [21]:
array2.size

12

In [22]:
array2.shape

(3, 4)

In [7]:
import pandas as pd
import matplotlib
print(pd.__version__)
print(matplotlib.__version__)

2.2.3
3.10.0
